apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda_cap_hello
  labels:
    app: uda_cap_hello
spec:
  progressDeadlineSeconds: 900
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
     labels:
        app: nginx
    spec:
      containers:
      - name: uda_cap_hello
        image: rluzardo/uda_cap_hello
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: uda_cap_hello 
  name: nginx-lb
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: uda_cap_hello
    group: uda_cap_hello
  type: LoadBalancer