apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  progressDeadlineSeconds: 900
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: nginx 
#  name: nginx-lb
#spec:
#  ports:
#  - protocol: TCP
#    port: 80
#    targetPort: 8080
#  selector:
#    app: nginx
#    group: nginx
#  type: LoadBalancer