apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacaphello
  labels:
    app: udacaphello
spec:
  progressDeadlineSeconds: 900
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
     labels:
        app: udacaphello
    spec:
      containers:
      - name: udacaphello
        image: rluzardo/uda_cap_hello
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udacaphello
  name: nginx-lb
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: udacaphello
    group: udacaphello
  type: LoadBalancer