
version: 2.1
orbs:
  # For slack alerts
  slack: circleci/slack@4.1
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@0.12.0

commands:
  
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      workflow_id:
        type: string
    steps:
      - run:
          name: Destroy environments
          no_output_timeout: 30m
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name capstone-${CIRCLE_WORKFLOW_ID}
            echo capstone-${CIRCLE_WORKFLOW_ID}
            #exit 1
jobs: 
  deploy_k8_cluster:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          command: |  
            yum -y install tar gzip      
      - run:
          name: Install dependencies
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
      - run:
          name: create cluster
          command: | 
            eksctl create cluster \
            --name k8-udacapstone \
            --version 1.20 \
            --region us-west-2 \
            --nodegroup-name udacaps-k8-nodes \
            --node-type t2.micro \
            --nodes 1
  
  easy-deploy:
      docker:
      - image: amazon/aws-cli
      steps:
        - checkout
        - run: 
            name: authenticate
            command: aws eks --region us-west-2 update-kubeconfig --name k8-udacapstone
        - run: 
            name: deployment 
            command: | 
              cd .circleci/files
              chmod +x run_kubernetes.sh
              ls -la
              ~/run_kubernetes.sh
  
  create-deploy:
    docker:
      - image: amazon/aws-cli
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - run: 
          name: authenticate
          command: aws eks --region us-west-2 update-kubeconfig --name k8-udacapstone
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: k8-udacapstone
          aws_region: us-west-2
          namespace: capstone

          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: .circleci/files/uda-capstone-dep.yml
          resource-name: deployment/myapp

  deploy_k8_deployment:
    docker:  
      - image: amazon/aws-cli
    steps:
      - checkout   
      - run:
          name: Install dependencies
          command: |
            yum -y group install 'Development Tools'
            yum -y install perl-core libtemplate-perl zlib-devel -y
            yum -y install wget
            wget -c https://www.openssl.org/source/openssl-1.0.2p.tar.gz
            tar -xzvf openssl-1.0.2p.tar.gz
            cd openssl-1.0.2p/
            ./config
            make
            make test
            make install
            cd /usr/local/ssl/
            ls -l
            /usr/local/ssl/bin/openssl version
            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
            /usr/local/ssl/bin/openssl sha1 -sha256 kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
            ls -la
            pwd
            kubectl version --short --client

      - run: 
          name: check cluster status
          command: | 
            cd /usr/local/ssl
            pwd
            ls -la
            aws eks --region us-west-2 update-kubeconfig --name k8-udacapstone
            /usr/local/ssl/kubectl cluster-info
            /usr/local/ssl/kubectl get nodes -o wide 

      - run:
          name: create deployment
          command: 
            cd /usr/local/ssl
            /usr/local/ssl/kubectl apply -f .circleci/files/uda-capstone-dep.yml

  deploy_client:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: creates infrastructure
          command: |
            aws cloudformation deploy --template-file .circleci/files/client.yml --tags project=udacity --stack-name capstone-${CIRCLE_WORKFLOW_ID} --parameter-overrides ID=client-${CIRCLE_WORKFLOW_ID} 
      - run: 
          command: |  
            yum -y install tar gzip
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            rm .circleci/ansible/inventory.txt # clears the inventory file to have only the existing instances
            echo "[web]" > .circleci/ansible/inventory.txt
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:project,Values=udacity" \
              --output text >> .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt
            ls ~/
      - persist_to_workspace:
          root: .circleci/ansible
          paths:
            - inventory.txt
      - destroy-environment:
          workflow_id: ${CIRCLE_WORKFLOW_ID}

  configure_client:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["41:6b:ff:3f:03:16:d6:a6:77:b9:d0:46:81:95:ca:83"]
      - attach_workspace:
          at: /tmp/.circleci/ansible
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
                python3 \
                py3-pip \
            && pip3 install --upgrade pip \
            && pip3 install \
                awscli \
            && rm -rf /var/cache/apk/*
            apk add --update ansible     
      - run:
          name: Configure server
          command: |
            cat .circleci/ansible/inventory.txt
            ansible-playbook -i /tmp/.circleci/ansible/inventory.txt .circleci/ansible/deploy-client.yml
      - destroy-environment:
          workflow_id: ${CIRCLE_WORKFLOW_ID}
          
workflows:
  default:
    jobs:
      #- deploy_k8_cluster
      #- create-deploy:
      #    cluster-name: k8-udacapstone
       - easy-deploy 
      #- deploy_k8_deployment
#          requires: [deploy_k8_cluster]
      #- deploy_client
#         requires: [deploy_k8_deployment]
#      - configure_client:
#           requires: [deploy_client, deploy_k8_cluster]
#      - test_connectivity:
#          requires: [deploy_client]
#      - send_logs:
#          requires: [test_connectivity]
#      - send_slack_alert:
#          requires: [test_connectivity]
#      


