apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacapblue-deployment
  labels:
    app: udacapblue
spec:
  progressDeadlineSeconds: 900
  replicas: 1
  selector:
    matchLabels:
      app: udacapblue
  template:
    metadata:
     labels:
        app: udacapblue
    spec:
      containers:
      - name: udacapblue
        image: rluzardo/udacap_blue
        ports:
        - containerPort: 80
