---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["python3", "zip"]
    state: latest
    update_cache: yes

- name: Creates directory
  file:
    path: ~/helloup
    state: directory

- name: "copy script"
  template:
    src: "files/capstone.py"
    dest: "~/helloup/capstone.py"

#- name: install aws cli
#  shell: |
#    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#    unzip awscliv2.zip
#    ./aws/install

- name: run curl
  environment:
    UDA_CAPSTONE_URL: "{{ lookup('env','UDA_CAPSTONE_URL')}}"
  shell: |
     curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
     chmod +x ./kubectl
     mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
     echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
     aws eks --region us-west-2 update-kubeconfig --name k8-udacapstone
     ./kubectl cluster-info
     ./kubectl get nodes -o wide 
     ./kubectl apply -f .circleci/files/uda-capstone-dep.yml
     ./kubectl get pods
     ./kubectl get svc
     export UDA_CAPSTONE_URL=$(./kubectl get svc udacaphello-load-balancer -o jsonpath='{.status.loadBalancer.ingress[*].hostname}') 
     echo $UDA_CAPSTONE_URL
  #ignore_errors: true

- name: run script
  shell: |
    python3 ~/helloup/capstone.py

- name: "copy logs"
  fetch:
    src: ~/helloup/log.txt
    dest: /tmp/log.txt
    
- name: check log
  shell:  tail ~/helloup/log.txt
  register: out

- debug: var=out.stdout_lines