apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacapgreen-deployment
  labels:
    app: udacapgreen
spec:
  progressDeadlineSeconds: 900
  replicas: 1
  selector:
    matchLabels:
      app: udacapgreen
  template:
    metadata:
     labels:
        app: udacapgreen
    spec:
      containers:
      - name: udacapgreen
        image: rluzardo/udacap_green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: udacapgreen-lb
spec:
  type: LoadBalancer
  selector:
    app: udacapgreen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  
